janet-lang/jaylib

project.janet
The build process was missing a few flags to correctly build on macOS.
=> Fix macOS build

project.janet
Add a missing GLFW include for windows.
After adding this include, I was able to run all of the tests successfullly
That missing GLFW include might also be needed on Linux.
=> Add GLFW include

test/test0.janet
Change out the visualization in test0.janet for something more calm, based on moving a point around the screen.
I also think the calmer visualization is more in line with the music. I realize this is just a test, but I tried to make it pleasing on the eyes (since I had the time/energy to do so).
=> Calm down the visualization in test0.janet

src/image.h
This is technically a breaking change, but I don't know what sort of stability guarantees Jaylib makes and this seems pretty uncontroversial.
=> fix typo: ansiotropic -> anisotropic

src/types.h
This might technically be a breaking change, but I think it's a pretty important bugfix.
Raylib's `Vector2` contains two floats, but Jaylib truncates those to integers when it returns them (note that they are parsed as floats correctly).
This can lead to some pretty confusing behavior -- not necessarily with any of the currently implemented functions that return vectors, but this prohibits wrapping some other Raylib functions that do not always return integers.
=> jaylib_wrap_vec2: don't truncate floats to integers

src/image.h
this is useful to render at a different resolution then the window.
```clojure
(use ../build/jaylib)
(set-trace-log-callback nil)
(init-window 800 600 "Test Game")
(set-target-fps 60)
(def target (load-render-texture 400 300))
(while (not (window-should-close))
(begin-texture-mode target)
(draw-circle 200 150 60 :black)
(end-texture-mode)
(begin-drawing)
(clear-background :white)
(draw-texture-ex (get-rendertexture-texture target) [0 0] 0 2 :white)
(end-drawing))
(close-window)
```
thank you for this great library! I'm open to any suggestions :)
=> add function to get RenderTexture inner texture field.

src/types.h
After doing some testing, it seems that jaylib_getcolor has the format of abgr.
bakpakin said
>I don't think that color order is abrg if I recall. I think I intentionally chose whatever raylib used, or simply picked something that made sense with hexcodes. If not, I don't recall why I set it up the way I did.
When trying with raylib, I got:
```
printf("%x\n", ColorToInt((Color){128, 64, 0, 255}));
// prints:
804000ff
```
Which implies it uses rgba. When looking at the Color struct, the order is rgba (https://github.com/raysan5/raylib/blob/master/examples/others/rlgl_standalone.c#L81-L87), and when I tried rendering text with color `(Color){255, 0, 0, 255}` it was red.
In addition to following raylib, using rgba makes it easier to copy hex colors from other tools like image editors. …
=> jaylib_getcolor hex abgr -> rgba

README.md
draw-circle-gradient's 'x' and 'y' arguments must be integers, but
get-mouse-position returns two floats.
Maybe it used to work with previous versions of Raylib, but I don't
think it's the case with 3.7.0.
Edit: Oh, heh, I'm sure it's related to this: https://github.com/janet-lang/jaylib/pull/24
=> Fix a bug in the example program

api.txt, src/core.h
Adds a binding to the Raylib function `bool IsCursorOnScreen(void)`[^1], represented here in Jaylib as `cursor-on-screen?`.
[^1]: Seen in the Core/cusor-related functions section of the cheatsheet: https://www.raylib.com/cheatsheet/cheatsheet.html
=> Add cursor-on-screen? binding

project.janet, src/3d.h, src/audio.h, src/core.h, src/gestures.h, src/image.h, src/text.h, test/test1.janet
This PR mostly contains changes to update to Raylib 4.0.0.
It isn't a complete update but rather attends to:
* filename changes,
* function name changes, and
* function removals
for what already exists in jaylib.
One existing jaylib test was changed to remove the use of `draw-text-rec` as the corresponding Raylib function `DrawTextRec` was removed in Raylib 4.0.0.
On a side note [Raylib's CHANGELOG](https://github.com/raysan5/raylib/blob/d4382f4a52e7631bf02ff8073ed24b282596ce0a/CHANGELOG) file was consulted to verify that most of the changes were expected.
There is also a change for removing a duplicate `draw-grid` -- this is unrelated to updating to Raylib 4.
=> Partial update to Raylib 4.0.0

src/3d.h, src/audio.h, src/core.h, src/gestures.h, src/image.h, src/shapes.h, src/text.h
Added function signatures and docstrings based on raylib cheat sheet: https://www.raylib.com/cheatsheet/cheatsheet.html
Now `(doc init-window)` (and other jaylib functions) returns helpful info when invoked in the REPL.
All tests still pass.
=> Add docstrings to jaylib functions

README.md, project.janet, src/3d.h, src/audio.h, src/core.h, src/image.h, src/shapes.h, src/text.h
I went through the official changelog of raylib releases after 4.0, and that's what came after this.
Not every new function from 4.2 and 4.5 has been added, only the ones which seemed really necessary by now (e.g. I skipped color manipulation functions added in 4.5), partially to not make this PR terribly huge and hard for reviewing.
=> Update to raylib 4.5

src/types.h
Missing `!` at `janet_cstrcmp`s.
=> Fix camera2d_get

api.txt, project.janet, src/main.c, src/shader.h, src/types.h, test/test6.fs, test/test6.janet, test/test6.vs
Bindings to load shaders and set common uniform types.
Took some inspiration from [this fork](https://github.com/ianthehenry/jaylib), though with a different approach to setting shader values (`(set-shader-value shader loc-index [1 2] :vec2)` vs `(set-shader-value-vec2 shader uniform-name [1 2])`). Not sure which implementation is considered more idiomatic?
=> Basic shader bindings

src/3d.h, src/shader.h
With this in place, jpm build no longer fails on macos.
=> fix build errors (macOS)

src/audio.h, src/text.h, src/types.h
Moved `jaylib_getunsignedcstring` from fonts to a general `types.h` since it is used in a similar interface in fonts' `LoadFontFromMemory`.
=> Add LoadMusicStreamFromMemory function

api.txt, src/image.h
https://github.com/raysan5/raylib/releases/tag/5.0
`GenImageGradientV` and `GenImageGradientH` were replaced with `GenImageGradientLinear`. I also added `GenImageGradientSquare` for completeness.
=> Upgrade to Raylib 5.0

src/types.h
As far as I'm aware, there is no way to retrieve a Texture2Ds width and height.
This should solve issue #51.
I came across the same problem, so here is a proposed fix.
=> Suggestion: Get texture2d width and height (issue #51)

src/text.h
This PR is an attempt to address #56.
The approach taken is for `load-font-ex` to also handle being called with 2 arguments (in addition to its existing ability to handle 3 arguments).
If called with 2 arguments, the 3rd and 4th arguments to `LoadFontEx` are set to `NULL` and `0` respectively.
---
I've made a demo in a fork.
If interested in trying, instructions are [here](https://github.com/sogaiu/jaylib/blob/load-font-ex-convenience-demo/demo.README) and the demo code file is [here](https://github.com/sogaiu/jaylib/blob/load-font-ex-convenience-demo/load-font-ex-demo.janet).
=> Address #56: two-argument load-font-ex

src/types.h
This is an attempt to address #64 by removing an extraneous trailing comma.
Formatting has also been tweaked slightly as well.
=> Address issue #64
